export interface MedicalCenterInterface{
  id:         number;
  // Generated by https://quicktype.io
  ok:         boolean;
  found:      number;
  name:       string;
  address:    string;
  phone:      number;
  stateId:    number;
  stateName:  string;
  cityId:     number;
  cityName:   string;
}
